### ISSUE TITLE
Download links on http://somanymachines.com/fargate/ is wrong

### ISSUE THREAD

**Issue by peterfox** [jpignata/fargate#1]
Link points to -> [https://github.com/jpignata/fargate/releases/download/v0.1.1/fargate-0.1.1-darwin-amd64.zip](https://github.com/jpignata/fargate/releases/download/v0.1.1/fargate-0.1.1-darwin-amd64.zip)

Should point to -> [https://github.com/jpignata/fargate/releases/download/v0.1.1/fargate--darwin-amd64.zip](https://github.com/jpignata/fargate/releases/download/v0.1.1/fargate--darwin-amd64.zip)

**Comment by jpignata** [comment]
*head in hands* I blew it.

Thanks so much! Fixed.

**Comment by peterfox** [comment]
👍
