### ISSUE TITLE
Easy installation for cli

### ISSUE THREAD

**Issue by ksteinbeck0405** [jpignata/fargate#12]
Having issues with automatic installation on CI/CD platform.
I can download the zip file via curl but am unable to successful extract it `End-of-central-directory signature not found`. 
So i had to download it through the UI and check in the executable in order to get it successfully installed on CI/CD platform.

**Comment by jpignata** [comment]
Hmm, that's a bummer. Which CI/CD platform are you using? What distribution mechanism would you like to see?

**Comment by ksteinbeck0405** [comment]
I'm using circleci. Do you have cli instructions for installation? Just wanting something (wget/curl/npm) that I can put in a script for installation on the box.
* your cli is awesome btw 👍

**Comment by jpignata** [comment]
Thanks so much!

I think I was able to get it working. My suspicion is that you need to follow redirects. Check out https://circleci.com/gh/jpignata/circleci-test/11 and https://github.com/jpignata/circleci-test/blob/master/.circleci/config.yml and let me know if that works for you on CircleCI 2.0.

Also, just a ⚠️ heads up ⚠️ this repo is likely going to move very shortly which may break your build. I'll make sure to reach out before that change happens.

**Comment by ksteinbeck0405** [comment]
Got it working. Appreciate the help and keeping me updated when this repo moves.

**Comment by josephfinlayson** [comment]
@jpignata you deleted the sample repo!

**Comment by ksteiny** [comment]
should be something like this
 ```- run:
          name: Release
          command: |
            curl -L -o fargate.zip https://github.com/jpignata/fargate/releases/download/v0.2.3/fargate-0.2.3-linux-amd64.zip
            unzip fargate.zip && sudo mv fargate /usr/local/bin```

**Comment by jritsema** [comment]
Related: may be a dumb question. @jpignata is there an automated build for this project?  In other words, where are the released binaries being built?  I didn't see any deploy step [here](https://github.com/jpignata/fargate/blob/master/.circleci/config.yml).

**Comment by jpignata** [comment]
Yeah - sorry - I killed it as I thought it served its purpose. Thanks @ksteiny!

@jritsema Nope - not currently. The last few releases I shipped manually. Automated releases are on my growing list :smile:
