### ISSUE TITLE
Document IAM permissions required per command

### ISSUE THREAD

**Issue by bugsbunny1996** [jpignata/fargate#19]
Hi, Can you post your IAM roles required for running a task by a user. I seem to have caught an error. Heres the error
```

[!] Couldn't register ECS task definition
AccessDeniedException: User: arn:aws:iam::*******:user/<username> is not author                                                                                                                     ized to perform: iam:PassRole on resource: arn:aws:iam::*********:role/ecsTas                                                                                                                     kExecutionRole
        status code: 400, request id: f31c6334-03e8-11e8-aaf9-1f6bfe37bc80
```

I am sure there will be more errors after i give the required IAMroles. Since, I'm not admin. I would like to know all the required IAM roles for running a docker on fargate. 

BTW, great project! loved it

**Comment by bugsbunny1996** [comment]
nvm, these are the inline permissions needed to be used used. 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1482712489000",
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:PutRolePolicy",
                "lambda:CreateFunction",
                "lambda:InvokeAsync",
                "lambda:InvokeFunction",
                "iam:PassRole",
                "lambda:UpdateAlias",
                "lambda:CreateAlias",
                "lambda:GetFunctionConfiguration",
                "lambda:AddPermission",
                "lambda:UpdateFunctionCode"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}


```

**Comment by jpignata** [comment]
Thanks for posting! At a glance, I'm a bit confused about all of the lambda:* permissions. Are you sure this is the document you meant to post?

**Comment by bugsbunny1996** [comment]
This solves my issue working at an organisation. It should help most people who would look for similar permissions. For a personal acc on aws, he would be admin.

**Comment by bugsbunny1996** [comment]
This solves my issue working at an organisation. It should help most people who would look for similar permissions. For a personal acc on aws, he would be admin.
