### ISSUE TITLE
Creating a service fails with previously working setup

### ISSUE THREAD

**Issue by edipetres** [jpignata/fargate#38]
I have been successfully using fargate for a while now, an awesome tool by the way!

However, yesterday it started throwing an error as if my credentials were not set up right:
```sh
[!] Could not create Cloudwatch Logs log group
SubscriptionRequiredException: The AWS Access Key Id needs a subscription for the service
	status code: 400, request id: 7f6464c9-16fe-11e8-b99d-2d585cda5bb0
```
I checked that the permissions on the AWS account did not change and the environment variables are available (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY) in the shell.

Since I have not changed anything in the environment where I ran the commands, I'm not sure what went wrong. Do you have any idea where else could the issue lie?

**Comment by jpignata** [comment]
Hmm, I haven't seen that before. That API error appears to indicate an
account issue. Can you ensure your account is in good standing by logging
in and looking on the billing panel for any kind of alert?

**Comment by edipetres** [comment]
Thank you for the quick response. The problem went away now, but could not trace back the exact issue, but I'm guessing it might have had something to do with the policies. Anyway, closing this for now, keep up the good work!
