### ISSUE TITLE
Expose multiple ports?

### ISSUE THREAD

**Issue by rafi-tvtime** [jpignata/fargate#51]
Is it possible to create/deploy a service with multiple ports exposed?
I think it would have to add additional targets with the addition ports to the target group that is created.

**Comment by jpignata** [comment]
You can only expose one port to a load balancer, but you can listen on any port you'd like. Does that make sense?

**Comment by rafi-tvtime** [comment]
Hmm, yeah I guess I didn't realize that. Although it seems like you ought to be able to due that with rules in the application load balancer, but I guess it's not supported. Thanks

**Comment by jpignata** [comment]
You can currently add multiple services to the same load balancer.
Currently ECS only supports a single target group per service and therefore
only supports a single port, AFAIK.

**Comment by devotox** [comment]
Actually ECS supports multiple ports in its definition.
And this is needed for my use case atm. I was able to make this work using the AWS CLI directly
ports 21 and 1000-10009 for FTP PASV

@jpignata
