### ISSUE TITLE
Ability to scale a service's desired tasks after creation

### ISSUE THREAD

**Issue by reginaldcampbell** [jpignata/fargate#58]
Please allow the cli to update the service to increase the desired task number after the service has been created. 
Right now, we can only set the desired task numbers upon creation for services.

**Comment by reginaldcampbell** [comment]
This was a matter of the asg scale-down policy overriding the fargate service scale command.  Closing issue.  Thanks!

**Comment by chjones** [comment]
Adding `ecs_autoscale_min_instances = "2"` to terraform.tfvars worked for me.
