### ISSUE TITLE
Enable new regions (3 more).

### ISSUE THREAD

**Issue by provtimofei** [jpignata/fargate#59]
According to https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/ there are 4 regions where fargate is supported now: 
Northern Virginia | Ohio | Oregon | Ireland
I made changes locally and everything works for me. I can share my changes - diff is attached.
diff --git a/README.md b/README.md
index 3ba3401..ab67bb1 100644
--- a/README.md
+++ b/README.md
@@ -13,8 +13,8 @@
 
 #### Region
 
-By default, fargate uses *us-east-1*. Also available  *us-west-2*, *us-east-2*, *eu-west-1*.
-The CLI accepts a --region parameter for future use and
+By default, fargate uses *us-east-1* as this is the single region where AWS
+Fargate is available. The CLI accepts a --region parameter for future use and
 will honor *AWS_REGION* and *AWS_DEFAULT_REGION* environment settings. Note that
 specifying a region where all required services aren't available will return an
 error.
diff --git a/cmd/root.go b/cmd/root.go
index bca26b2..994ed22 100644
--- a/cmd/root.go
+++ b/cmd/root.go
@@ -45,7 +45,7 @@ CPU (CPU Units)    Memory (MiB)
 4096               8192 through 30720 in 1GiB increments
 `)
 
-var validRegions = []string{"us-east-1", "us-west-2", "us-east-2", "eu-west-1"}
+var validRegions = []string{"us-east-1"}
 
 var (
        clusterName string
@@ -105,16 +105,12 @@ CloudWatch Logs, and Amazon Route 53 into an easy-to-use CLI.`,
                        }
                }
 
-               region_is_valid := false
                for _, validRegion := range validRegions {
                        if region == validRegion {
-                               region_is_valid = true
                                break
                        }
-               }
-               
-               if !region_is_valid {
-                       console.IssueExit("Invalid region: '%s' [valid regions: %s]", region, strings.Join(validRegions, ", "))
+
+                       console.IssueExit("Invalid region: %s [valid regions: %s]", region, strings.Join(validRegions, ", "))
                }
 
                config := &aws.Config{

**Comment by rnzsgh** [comment]
+1

**Comment by bitmatix** [comment]
+1 for eu-central-1

**Comment by Melbit-haixingzhang** [comment]
+1 for ap-southeast-2

**Comment by mgajda** [comment]
+1
Added patch with all currently supported #62.

**Comment by gliptak** [comment]
There are four PRs on this

https://github.com/jpignata/fargate/pull/54
https://github.com/jpignata/fargate/pull/55
https://github.com/jpignata/fargate/pull/61
https://github.com/jpignata/fargate/pull/62

**Comment by mgajda** [comment]
Counting each one as :+1: , you can see that the author has no time to maintain this software.
Feel free to pull from https://github.com/mgajda/fargate.

**Comment by mgajda** [comment]
@jpignata I will review and triage outstanding issues, if you give me commit bit. Having two or three more maintainers would indeed make sure that there is some response even in vacation periods :-).

**Comment by sebastianfuss** [comment]
Hi @jpignata, @mgajda 

is it possible to make a new release?

Thanks a lot in advance!
Sebastian.
