### ISSUE TITLE
Cut New Release

### ISSUE THREAD

**Issue by osterman** [jpignata/fargate#67]
## what
* Last release was cut in january

## why
* One month ago, cli was updated to support new regions; current release does not support `us-west-2`
* Most users will use the binary release rather than build their own from source

## references
* https://github.com/jpignata/fargate/pull/62#issuecomment-424065609

**Comment by brikis98** [comment]
+1

**Comment by bluengreen** [comment]
+10

**Comment by osterman** [comment]
We've built binary releases based on master. Since this is a fork, we've restarted our releases at `0.1.0` since it's impossible to maintain parity.

**Comment by tisba** [comment]
Is there something we can do to help to cut a new release, @jpignata?

**Comment by Siilwyn** [comment]
@PaulMaddox this is done now right? :tada:

**Comment by PaulMaddox** [comment]
Yes, see the github releases page 👍🥳
