### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by Siilwyn** [jpignata/fargate#76]
Sorry to bother, but is this still being maintained? Thinking of using this for a project but since the last release is more than a year ago I'm wondering if this is still an active project.

**Comment by jpignata** [comment]
Hey Siilwyn! No bother at all. I'm not actively using this and haven't had time to revisit the project -- so I am thinking of archiving it and allowing folks interested to fork it and build on it elsewhere if desired. Hope that helps clarify.

**Comment by Siilwyn** [comment]
Alright thank you for clarifying! If you don't mind sharing & if applicable, what solution are you using to replace this?

**Comment by wilsonodk** [comment]
@Siilwyn Turner Broadcasting has [a fork](https://github.com/turnerlabs/fargate) that is actively maintained. It does not have the full suite of features that the original supported, but depending on your use case, it may fill your need. We have lots of teams that use it daily.

**Comment by jpignata** [comment]
Awesome. I will do that!

I’m not using AWS Fargate or Amazon ECS actively at the moment.
