### ISSUE TITLE
Fargate is available in more regions than us-east-1

### ISSUE THREAD

**Issue by jorgeluishdez** [jpignata/fargate#78]
Fargate is available in more regions than us-east-1, and --region option is not working

**Comment by yiwong2001** [comment]
I got exact same problem

[root@filer1 docker]# fargate lb create livedashtest --port 8080 --region=eu-west-1
[!] Invalid region: eu-west-1 [valid regions: us-east-1]

:(

**Comment by 178inaba** [comment]
I also encountered this issue.
I confirmed that in `v0.2.3`, only `us-east-1` was permitted in the region, but it was fixed in master.
You can do `go get` if you have a golang environment.

```console
$ go get -u github.com/jpignata/fargate
```

v0.2.3
https://github.com/jpignata/fargate/blob/e803b0e213c630e02b69afaa3d7bba3b0dd061d4/cmd/root.go#L45

master
https://github.com/jpignata/fargate/blob/d1a9e151ad4a5ea164ca029f0bf019cdf2e25781/cmd/root.go#L48

@jpignata Is it possible to release a new version?

**Comment by PaulMaddox** [comment]
John has moved on to a different area of Amazon, and therefore isn't heavily involved in the AWS Containers side anymore. He has just given me rights to the repo though - so I will start reviewing/merging PRs and cut a release early next week

**Comment by osterman** [comment]
@PaulMaddox thanks for the update!

**Comment by PaulMaddox** [comment]
Closing this issue, as a new release (v0.3.0) has now been cut that includes additional region support:

https://github.com/jpignata/fargate/releases

**Comment by Zefool** [comment]
I think this is not quite fixed yet. At least the README is not yet up to date.

**Comment by Zefool** [comment]
@PaulMaddox

**Comment by caleb-tt** [comment]
more regions support Fargate, not listed in v0.3.0 -
ca-central-1, ap-northeast-2, ap-south-1

**Comment by mariocannistra** [comment]
please add also region  eu-west-3 ...

using current latest version https://github.com/jpignata/fargate/releases/tag/v0.3.1

i get the following error message:

```
$ fargate task list --region eu-west-3

[!] Invalid region: eu-west-3 [valid regions: ap-northeast-1, ap-northeast-2, ap-south-1, ap-southeast-1, ap-southeast-2, ca-central-1, eu-central-1, eu-west-1, eu-west-2, us-east-1, us-east-2, us-west-1, us-west-2]
```

thank you,
mario
