### ISSUE TITLE
Allow roles to be specified for tasks and services

### ISSUE THREAD

**Issue by jpignata** [jpignata/fargate#8]

**Comment by jesseproudman** [comment]
Hi John!

We've got a Task Description that has a role pre-set, and when we update it with Fargate, that role gets lost. Is that the expected behavior? Seems like it should leave whatever role we had set, set but I'm not sure how it's stored on the AWS side.

**Comment by jpignata** [comment]
Yeah, that'd be consistent with this issue. Each deploy is a new revision of the task definition, and my first cut didn't take into account task roles. I'll see if I can get this out prior to 0.3.0 in a quick fix. Sorry about that!

**Comment by jesseproudman** [comment]
No worries. I can't complain about bugs in OSS. :)

If you could get a fix out sooner rather than later, that'd be amazing. Every time we push code, it wipes that role which then breaks our deploy, so we're sorta stuck. Can work on a workaround if you think it'll be a bit though.

**Comment by jpignata** [comment]
I'll get a fix out before the weekend is up.

**Comment by jesseproudman** [comment]
Excellent. Thanks John!

**Comment by jpignata** [comment]
Fixed in [0.2.3](https://github.com/jpignata/fargate/releases/tag/v0.2.3).

**Comment by jesseproudman** [comment]
You rock!
